version: '3'

services:
  mongodb:
    image: mongo:3.1
    ports: 
      - 27017:27017

  bet-miner:
    build: 
      dockerfile: Dockerfile
      context: .
    ports:
      - 3000:3000
    environment: 
      - DB_CONNECTION=mongodb://mongodb:27017/BetMiner

